name: Hourly Market Zone Scanner
on:
  schedule:
    - cron: '0 * * * *' # Yeh har ghante automatic run hoga
  workflow_dispatch: # Isse aap jab chahein manually bhi run kar sakte hain
jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout Repository
      uses: actions/checkout@v3
    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'
    - name: Install Dependencies
      run: |
        pip install pandas yfinance requests
    - name: Run Scanner Pipeline
      run: |
        python pipeline.py
